/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AcademicCredential {
  export type CredentialStruct = {
    studentName: string;
    degree: string;
    institution: string;
    issueDate: BigNumberish;
  };

  export type CredentialStructOutput = [
    studentName: string,
    degree: string,
    institution: string,
    issueDate: bigint
  ] & {
    studentName: string;
    degree: string;
    institution: string;
    issueDate: bigint;
  };
}

export interface AcademicCredentialInterface extends Interface {
  getFunction(
    nameOrSignature: "admin" | "getCredentials" | "issueCredential"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCredentials",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [AddressLike, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
}

export interface AcademicCredential extends BaseContract {
  connect(runner?: ContractRunner | null): AcademicCredential;
  waitForDeployment(): Promise<this>;

  interface: AcademicCredentialInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getCredentials: TypedContractMethod<
    [student: AddressLike],
    [AcademicCredential.CredentialStructOutput[]],
    "view"
  >;

  issueCredential: TypedContractMethod<
    [
      student: AddressLike,
      studentName: string,
      degree: string,
      institution: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCredentials"
  ): TypedContractMethod<
    [student: AddressLike],
    [AcademicCredential.CredentialStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [
      student: AddressLike,
      studentName: string,
      degree: string,
      institution: string
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
