/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AcademicCredential } from "./AcademicCredential";
export * as factories from "./factories";
export { AcademicCredential__factory } from "./factories/AcademicCredential__factory";
